import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  headerLeft: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--accent)", fontWeight: 500 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 200,
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
    minWidth: 0,
  } satisfies CSSProperties,
  hint: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 16,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    cursor: "grab",
    transition: "border-color 120ms ease, opacity 120ms ease, box-shadow 120ms ease",
  } satisfies CSSProperties,
  rowDragging: {
    opacity: 0.55,
    cursor: "grabbing",
  } satisfies CSSProperties,
  rowDropTarget: {
    borderColor: "var(--accent)",
    boxShadow: "inset 0 0 0 1px var(--accent)",
  } satisfies CSSProperties,
  rowBusy: {
    cursor: "not-allowed",
    opacity: 0.7,
  } satisfies CSSProperties,
  rowDisabled: {
    opacity: 0.55,
  } satisfies CSSProperties,
  handle: {
    display: "inline-flex",
    alignItems: "center",
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  name: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    textDecoration: "none",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 4, marginLeft: "auto" } satisfies CSSProperties,
  empty: { fontSize: 14, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
