import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard (mockup layout). */
export const s = {
  card: (borderColor: string, muted: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 20,
    padding: "18px 20px",
    borderRadius: 10,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderWidth: 1,
    borderLeftWidth: 3,
    borderLeftColor: borderColor,
    background: "var(--bg-elevated)",
    opacity: muted ? 0.55 : 1,
    transition: "opacity .2s",
  }),
  main: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  ruleRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
  } satisfies CSSProperties,
  rule: {
    margin: 0,
    fontStyle: "italic",
    color: "var(--text-primary)",
    fontSize: 15,
    lineHeight: 1.45,
    fontWeight: 500,
  } satisfies CSSProperties,
  editRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    width: "100%",
  } satisfies CSSProperties,
  editInput: {
    flex: 1,
    padding: "6px 10px",
    border: "1px solid var(--border)",
    borderRadius: 6,
    fontSize: 14,
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  chips: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  evidence: {
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  evidencePath: {
    fontSize: 12,
    color: "var(--text-secondary)",
    fontVariantNumeric: "tabular-nums",
  } satisfies CSSProperties,
  copyBtn: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-muted)",
    cursor: "pointer",
  } satisfies CSSProperties,
  evidencePre: {
    margin: 0,
    padding: "10px 12px",
    fontSize: 12,
    lineHeight: 1.55,
    overflow: "auto",
    whiteSpace: "pre-wrap",
    maxHeight: 140,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    maxWidth: 280,
  } satisfies CSSProperties,
  support: {
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "stretch",
    flexShrink: 0,
    minWidth: 128,
  } satisfies CSSProperties,
  actionBtn: {
    width: "100%",
    justifyContent: "center",
  } satisfies CSSProperties,
} as const;
