import type { CSSProperties } from "react";
import { PREVIEW_SIDEBAR_WIDTH } from "./constants";

export const s = {
  wrap: { maxWidth: "100%", minWidth: 0 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  headerLeft: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--accent)", fontWeight: 500 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 11px",
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-surface)",
    width: 220,
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
    minWidth: 0,
  } satisfies CSSProperties,
  hint: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 12,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  warning: {
    fontSize: 13,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 8,
    padding: "10px 12px",
    margin: 0,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  tokens: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums",
  } satisfies CSSProperties,
  dir: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
    maxWidth: 180,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  fileIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowDragging: { opacity: 0.55, cursor: "grabbing" } satisfies CSSProperties,
  rowDropTarget: {
    borderColor: "var(--accent)",
    boxShadow: "inset 0 0 0 1px var(--accent)",
  } satisfies CSSProperties,
  rowBusy: { cursor: "not-allowed", opacity: 0.7 } satisfies CSSProperties,
  handle: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    flexShrink: 0,
    cursor: "grab",
    width: 14,
    minHeight: 14,
  } satisfies CSSProperties,
  path: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  empty: { fontSize: 14, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
  } satisfies CSSProperties,
  footerTokens: {
    fontSize: 13,
    color: "var(--text-secondary)",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 600,
  } satisfies CSSProperties,
  injectNote: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  sidebar: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    width: PREVIEW_SIDEBAR_WIDTH,
    maxWidth: "94vw",
    zIndex: 40,
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: "var(--border-strong)",
    boxShadow: "var(--shadow-drawer)",
    animation: "ddslidein .2s cubic-bezier(.2,.7,.3,1)",
  } satisfies CSSProperties,
  sidebarHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "16px 18px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
    flexShrink: 0,
  } satisfies CSSProperties,
  sidebarTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    lineHeight: 1.4,
    wordBreak: "break-all",
  } satisfies CSSProperties,
  sidebarBody: {
    flex: 1,
    overflow: "auto",
    padding: "28px 32px 40px",
    minHeight: 0,
  } satisfies CSSProperties,
} as const;
