import type { CSSProperties } from "react";

export const s = {
  page: {
    padding: "24px 28px 40px",
    maxWidth: 720,
    margin: "0 auto",
  } satisfies CSSProperties,
  title: {
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    margin: 0,
    lineHeight: 1.3,
  } satisfies CSSProperties,
  subtitle: {
    color: "var(--text-secondary)",
    fontSize: 13,
    marginTop: 4,
    marginBottom: 22,
  } satisfies CSSProperties,
  step: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  } satisfies CSSProperties,
  stepBody: { marginLeft: 32, marginBottom: 24 } satisfies CSSProperties,
  badge: {
    width: 22,
    height: 22,
    borderRadius: 99,
    fontSize: 12,
    fontWeight: 700,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  stepLabel: { fontSize: 13.5, fontWeight: 600 } satisfies CSSProperties,
  linkBtn: {
    marginLeft: "auto",
    border: "none",
    background: "transparent",
    color: "var(--accent-text)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  emptyPanel: {
    marginLeft: 32,
    padding: "34px 20px",
    borderRadius: 10,
    border: "1px dashed var(--border-strong)",
    background: "var(--bg-elevated)",
    textAlign: "center",
  } satisfies CSSProperties,
  emptyIcon: {
    width: 42,
    height: 42,
    borderRadius: 11,
    background: "var(--bg-hover)",
    display: "grid",
    placeItems: "center",
    margin: "0 auto 12px",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginTop: 26,
    marginLeft: 32,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  aggregate: {
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
};
