import type { CSSProperties } from "react";

export const s = {
  page: { padding: "0 0 40px" } satisfies CSSProperties,
  header: {
    padding: "18px 28px 4px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  configBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  title: {
    fontSize: 20,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    margin: 0,
  } satisfies CSSProperties,
  subtitle: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  modeSwitch: {
    marginLeft: "auto",
    display: "flex",
    gap: 2,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: 2,
  } satisfies CSSProperties,
  modeBtn: {
    padding: "4px 12px",
    fontSize: 11.5,
    fontWeight: 600,
    borderRadius: 5,
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  meta: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 28px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  columns: {
    display: "grid",
    gap: 12,
    padding: "20px 28px 0",
  } satisfies CSSProperties,
  column: {
    border: "1px solid var(--border)",
    borderRadius: 9,
    background: "var(--bg-elevated)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: 0,
  } satisfies CSSProperties,
  colHead: {
    padding: 12,
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "center",
    gap: 9,
  } satisfies CSSProperties,
  colBody: {
    padding: 12,
    display: "flex",
    flexDirection: "column",
    gap: 7,
    flex: 1,
  } satisfies CSSProperties,
  colFoot: {
    padding: "9px 12px",
    borderTop: "1px solid var(--border)",
    background: "var(--bg-surface)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  finding: {
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  findingTitle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: 1.3,
  } satisfies CSSProperties,
  findingFile: { fontSize: 10.5, color: "var(--text-muted)", marginTop: 4 } satisfies CSSProperties,
  tabBar: {
    display: "flex",
    gap: 2,
    padding: "0 28px",
    borderBottom: "1px solid var(--border)",
    overflowX: "auto",
  } satisfies CSSProperties,
  tab: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "12px 16px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    whiteSpace: "nowrap",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  tabDetail: { padding: "20px 28px", maxWidth: 760 } satisfies CSSProperties,
  summaryCard: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "14px 16px",
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    marginBottom: 18,
  } satisfies CSSProperties,
  disagreeWrap: { padding: "22px 28px 0" } satisfies CSSProperties,
  loc: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  locHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  take: { padding: "10px 14px", background: "var(--bg-elevated)" } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "12px 28px" } satisfies CSSProperties,
};
