import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: "16px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  cardCompact: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: "12px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  } satisfies CSSProperties,
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    minWidth: 0,
  } satisfies CSSProperties,
  titleIcon: {
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  title: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  summary: {
    fontSize: 14,
    fontStyle: "italic",
    color: "var(--text)",
    lineHeight: 1.55,
    margin: 0,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  columns: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 20,
    alignItems: "start",
  } satisfies CSSProperties,
  column: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  colHead: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  colTitleIn: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--ok)",
  } satisfies CSSProperties,
  colTitleOut: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  list: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  listItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  bulletIn: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--ok)",
    marginTop: 6,
    flexShrink: 0,
  } satisfies CSSProperties,
  bulletOut: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--text-muted)",
    marginTop: 6,
    flexShrink: 0,
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  divider: {
    height: 1,
    background: "var(--border)",
    border: "none",
    margin: "2px 0",
  } satisfies CSSProperties,
  risksBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  risksHead: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  risksTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  riskRowWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  riskRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg)",
  } satisfies CSSProperties,
  riskMain: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
    flex: 1,
  } satisfies CSSProperties,
  riskTitle: {
    fontSize: 13,
    color: "var(--text)",
    lineHeight: 1.35,
  } satisfies CSSProperties,
  riskRefs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  fileLink: {
    border: "none",
    background: "transparent",
    padding: 0,
    fontSize: 12,
    color: "var(--accent-text)",
    cursor: "pointer",
    textDecoration: "underline",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  riskLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  riskChevronBtn: {
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "pointer",
    display: "inline-flex",
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  riskChevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    flexShrink: 0,
    transform: open ? "rotate(0deg)" : "rotate(-90deg)",
    transition: "transform 120ms ease",
  }),
  riskExplanation: {
    margin: "0 12px 2px",
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  muted: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  skeletonWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
} as const;
