import type { CSSProperties } from "react";
import { PREVIEW_SIDEBAR_WIDTH } from "./constants";

export const s = {
  page: {
    padding: "28px 32px 56px",
    maxWidth: 1180,
    margin: "0 auto",
  } satisfies CSSProperties,
  layout: {
    display: "flex",
    alignItems: "flex-start",
    gap: 36,
  } satisfies CSSProperties,
  mainCol: {
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 22,
    gap: 16,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  title: {
    fontSize: 22,
    fontWeight: 600,
    margin: 0,
    lineHeight: 1.3,
  } satisfies CSSProperties,
  repoName: {
    color: "var(--accent-text)",
    fontWeight: 650,
  } satisfies CSSProperties,
  subtitle: {
    color: "var(--text-secondary)",
    fontSize: 13,
    marginTop: 6,
    marginBottom: 0,
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  banner: {
    fontSize: 13,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 8,
    padding: "10px 12px",
    margin: "0 0 16px",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  pending: {
    fontSize: 13,
    color: "var(--text-secondary)",
    margin: "0 0 16px",
  } satisfies CSSProperties,
  toc: {
    position: "sticky",
    top: 24,
    width: 196,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    paddingTop: 6,
  } satisfies CSSProperties,
  tocLabel: {
    fontSize: 11,
    fontWeight: 650,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 10,
  } satisfies CSSProperties,
  tocLink: {
    display: "block",
    fontSize: 13,
    lineHeight: 1.35,
    padding: "7px 8px 7px 12px",
    color: "var(--text-secondary)",
    textDecoration: "none",
    borderLeftWidth: 2,
    borderLeftStyle: "solid",
    borderLeftColor: "transparent",
  } satisfies CSSProperties,
  tocLinkActive: {
    color: "var(--text-primary)",
    borderLeftColor: "var(--accent)",
    fontWeight: 600,
  } satisfies CSSProperties,
  sections: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  card: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: "14px 18px 18px",
    scrollMarginTop: 24,
  } satisfies CSSProperties,
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: "inherit",
    textAlign: "left",
  } satisfies CSSProperties,
  cardIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    display: "grid",
    placeItems: "center",
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    flexShrink: 0,
  } satisfies CSSProperties,
  cardTitle: {
    fontSize: 16,
    fontWeight: 650,
    margin: 0,
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  chevron: {
    color: "var(--text-muted)",
    flexShrink: 0,
    transition: "transform 0.15s ease",
  } satisfies CSSProperties,
  cardBody: {
    marginTop: 14,
  } satisfies CSSProperties,
  layoutTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-secondary)",
    margin: "14px 0 8px",
  } satisfies CSSProperties,
  tree: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  flowCard: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    padding: "12px 14px",
    marginTop: 10,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  flowTitle: {
    fontSize: 14,
    fontWeight: 650,
    margin: "0 0 8px",
  } satisfies CSSProperties,
  steps: {
    margin: 0,
    paddingLeft: 18,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  stepRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  cmdRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  } satisfies CSSProperties,
  cmd: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    overflowX: "auto",
  } satisfies CSSProperties,
  envList: {
    margin: "8px 0 0",
    paddingLeft: 18,
    fontSize: 13,
  } satisfies CSSProperties,
  readingItem: {
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    padding: "10px 0",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  readingNum: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--accent)",
    minWidth: 22,
    paddingTop: 2,
  } satisfies CSSProperties,
  startMark: {
    fontSize: 11,
    fontWeight: 650,
    color: "var(--ok)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  nextMark: {
    fontSize: 11,
    fontWeight: 650,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  note: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginTop: 4,
  } satisfies CSSProperties,
  taskGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: 12,
    marginTop: 12,
  } satisfies CSSProperties,
  taskCard: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    padding: "12px 14px",
    background: "var(--bg-surface)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  taskTitle: { fontSize: 14, fontWeight: 650, margin: 0 } satisfies CSSProperties,
  taskPath: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  emptyIn: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: "8px 0 0",
  } satisfies CSSProperties,
  intro: {
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    margin: "0 0 4px",
  } satisfies CSSProperties,
  skeletons: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "24px 32px 44px",
    maxWidth: 1100,
    margin: "0 auto",
  } satisfies CSSProperties,
  sidebar: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    width: PREVIEW_SIDEBAR_WIDTH,
    maxWidth: "94vw",
    zIndex: 40,
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: "var(--border-strong)",
    boxShadow: "var(--shadow-drawer)",
  } satisfies CSSProperties,
  sidebarHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "16px 18px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
    flexShrink: 0,
  } satisfies CSSProperties,
  sidebarTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    lineHeight: 1.4,
    wordBreak: "break-all",
  } satisfies CSSProperties,
  sidebarBody: {
    flex: 1,
    overflow: "auto",
    padding: "16px 18px 32px",
    minHeight: 0,
  } satisfies CSSProperties,
  pre: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } satisfies CSSProperties,
} as const;
