import type { CSSProperties } from "react";

export const s = {
  page: {
    display: "flex",
    flexDirection: "column",
    height: "calc(100vh - 52px)",
    minHeight: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  title: {
    fontSize: 18,
    fontWeight: 600,
    margin: 0,
    padding: "16px 20px 12px",
    lineHeight: 1.3,
    flexShrink: 0,
  } satisfies CSSProperties,
  split: {
    display: "grid",
    gridTemplateColumns: "minmax(240px, 300px) minmax(0, 1fr)",
    flex: 1,
    minHeight: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
  } satisfies CSSProperties,
  explorer: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: "var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    padding: "6px 8px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
    flexShrink: 0,
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    overflow: "auto",
    minHeight: 0,
    flex: 1,
    padding: "6px 0",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 12px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  rowActive: {
    background: "var(--accent-bg)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  path: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  fileIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  fileInput: { display: "none" } satisfies CSSProperties,
  fileError: {
    fontSize: 12,
    color: "var(--crit)",
    padding: "4px 12px 8px",
    flexShrink: 0,
  } satisfies CSSProperties,
  listEmpty: {
    padding: "16px 12px",
    color: "var(--text-muted)",
    fontSize: 13,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  listEmptyTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-secondary)",
    margin: "0 0 6px",
  } satisfies CSSProperties,
  listEmptyBody: { margin: 0 } satisfies CSSProperties,
  footer: {
    flexShrink: 0,
    padding: "8px 12px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    fontSize: 11,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  preview: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: 0,
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
  previewHeader: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)",
    alignItems: "center",
    gap: 12,
    padding: "10px 16px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
    flexShrink: 0,
    minHeight: 72,
  } satisfies CSSProperties,
  previewTitle: {
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  headerRight: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 14,
    minWidth: 0,
  } satisfies CSSProperties,
  usedBy: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  modeToggle: {
    display: "inline-flex",
    alignItems: "center",
    background: "var(--bg-hover)",
    borderRadius: 8,
    padding: 3,
    justifySelf: "center",
  } satisfies CSSProperties,
  modeBtn: {
    padding: "5px 14px",
    borderRadius: 6,
    border: "none",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    lineHeight: 1.2,
  } satisfies CSSProperties,
  modeBtnOn: {
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    boxShadow: "0 1px 2px rgba(0,0,0,.28)",
  } satisfies CSSProperties,
  modeBtnOff: {
    background: "transparent",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  coverage: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
  } satisfies CSSProperties,
  coverageLabel: {
    fontSize: 9,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  previewBody: {
    flex: 1,
    overflow: "auto",
    padding: "32px 40px 48px",
    minHeight: 0,
  } satisfies CSSProperties,
  editor: {
    flex: 1,
    overflow: "auto",
    minHeight: 0,
    padding: 0,
  } satisfies CSSProperties,
  textarea: {
    width: "100%",
    height: "100%",
    minHeight: 240,
    resize: "none",
    padding: "20px 24px",
    border: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.6,
    outline: "none",
  } satisfies CSSProperties,
  previewEmpty: {
    color: "var(--text-muted)",
    fontSize: 14,
    margin: 0,
    padding: 24,
  } satisfies CSSProperties,
  skeletons: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "24px 32px 44px",
  } satisfies CSSProperties,
} as const;
